paths:
  test_data: "C:/Users/{user_name}/all_data_2/nnUNet/rawdata/ipcai2021_ALL_Test"
  output_data: "C:/Users/{user_name}/all_data_2/nnUNet/rawdata/ipcai2021_ALL_Test/Task22_ipcai2021__CTPelvic1K__fold0_2d_pred"
settings:
  task: "Task22_ipcai2021"
  fold: 0
  gpu: 0
  num_preprocessing_threads: 8
  num_save_threads: 4
